[DRAFT] [RAI-15293, RAI-15242, RAI-15310] raycast make smart habit actions respect override setting / Unify how we display events with Emojis / fail API errors silently
reclaim-ai/raycast-extension-fork pull request #4
Opened 2024-08-14 00:55 UTC by clayton-knapp

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-15 01:22 UTC, ajohnson1200 approved these changes

2024-08-15 20:45 UTC, SandyGifford requested changes

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/hooks/useEvent.tsx
> +  if (error) console.error("Error while fetching Events", error);
for a future PR

https://linear.app/reclaim/issue/RAI-15323/build-raycast-api-tools

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/hooks/useEvent.tsx
> +
in some contexts it looks like `getEventActions` is called once-per-frame.  Might be better to make a normalized mapping of smart habits to their lineage IDs so you can look them up quickly.

either:

```typescript
  const smartHabitsByLineageId = useMemo(
    () =>
      smartHabits?.reduce(
        (map, habit) =>
          habit.lineageId
            ? {
                ...map,
                [habit.lineageId]: habit,
              }
            : map,
        {} as { readonly [LINEAGE_ID in string]: SmartHabit }
      ) || {},
    []
  );
```

or grab `normalize` from the main app's `utils/objects` file

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/hooks/useSmartHabits.tsx
> +  } = useFetch<[SmartHabit]>(`${apiUrl}/smart-habits`, {
this type would be a single smart habit alone in an array

```suggestion
  } = useFetch<SmartHabit[]>(`${apiUrl}/smart-habits`, {
```

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/utils/string.ts
> +export function testTextForEmoji(text: string) {
```suggestion
export function getFirstEmojiFromString(text: string) {
```

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/utils/string.ts
> +  } catch (e) {
What's the expected failure state here?  [`exec` returns `null` if it finds nothing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec)

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/utils/string.ts
> +export function testTextForEmoji(text: string) {
Add an explicate return type (right now your implicit type is `RegExpExecArray | null`)

2024-08-15 20:45 UTC, SandyGifford commented on extensions/reclaim-ai/src/utils/string.ts
> +export function stripPlannerEmojis(text: string): { textWithoutEmoji: string } {
Why not return just `string`?

2024-08-15 23:19 UTC, clayton-knapp commented on extensions/reclaim-ai/src/utils/string.ts
> +  } catch (e) {
Thats a good question. Daniel added the try/catch a while back, you can read the explanation in his [PR](https://github.com/reclaim-ai/reclaim-worklifecalendar/pull/3337). But if `exec` just returns null maybe this second logic should be in a conditional like `if (emoji === null)`

2024-08-15 23:55 UTC, clayton-knapp commented on extensions/reclaim-ai/src/hooks/useEvent.tsx
> +
good idea

2024-08-16 00:13 UTC, SandyGifford reviewed
Almost there, just a few small things

2024-08-16 00:13 UTC, SandyGifford commented on extensions/reclaim-ai/src/hooks/useSmartHabits.tsx
> +  const smartHabitsByLineageIdsMap = useMemo(() => (smartHabits ? normalize(smartHabits, "lineageId") : undefined), []);
Careful, this may seem like it works, but [`useFetch`](https://developers.raycast.com/utilities/react-hooks/usefetch) caches the results between runs.  This means that `smartHabits` will be `undefined` or out of date if you don't add it to the dependency list.

```suggestion
  const smartHabitsByLineageIdsMap = useMemo(() => (smartHabits ? normalize(smartHabits, "lineageId") : undefined), [smartHabits]);
```

2024-08-16 00:13 UTC, SandyGifford commented on extensions/reclaim-ai/src/notifications.tsx
> +      const eventString = stripPlannerEmojis(realEventTitle);
Missed this last time, but we shouldn't run this function twice like this.  Store it in a variable.

2024-08-16 00:13 UTC, SandyGifford commented on extensions/reclaim-ai/src/utils/string.ts
> +export function getFirstEmojiFromString(text: string): RegExpExecArray | null {
I think ideally this should return `string | undefined`

2024-08-16 00:13 UTC, SandyGifford commented on extensions/reclaim-ai/tsconfig.json
> -    "strict": true,
Let's keep this `true`.  I can help you figure out how to deal with whatever grief its giving you tomorrow.

2024-08-16 00:34 UTC, SandyGifford approved these changes
looks good!  Thanks for taking the time to hit all of my comments.

2024-08-16 18:27 UTC, merged